Cleanup
cuberite/cuberite.github.io pull request #106
Opened 2022-01-29 12:20 UTC by tigerw

Minor changes:
* Group related styles together in CSS
* Try to make the architecture names consistent to ones without spaces

2022-01-29 16:49 UTC, mathiascode approved these changes
Thanks, looks fine. I don't have a strong opinion on the naming, but I'll leave that to @bearbin.

2022-01-29 17:15 UTC, bearbin requested changes

2022-01-29 17:15 UTC, bearbin commented on download-links.html
> +<li>x86-64: <a href="https://download.cuberite.org/darwin-x86_64/Cuberite.tar.gz">https://download.cuberite.org/darwin-x86_64/Cuberite.tar.gz</a></li>
What did I say in the last PR. IIAB, DFI! I can't see any benefit to changing these: they are perfectly legible for all our users, and the proposed replacements are not any more consistent (in fact, less so than before!).

2022-01-29 17:15 UTC, bearbin commented on index.html
>  							<a href="https://download.cuberite.org/linux-x86_64/Cuberite.tar.gz">64-bit</a>
```suggestion
							<a href="https://download.cuberite.org/linux-i386/Cuberite.tar.gz">x86 32-bit</a>
							<a href="https://download.cuberite.org/linux-x86_64/Cuberite.tar.gz">x86 64-bit</a>
```

Now we have an ARM 64 bit, we do actually need to add this, for disambiguation.

2022-01-30 17:07 UTC, tigerw commented
Broken is in the eye of the beholder, as they say. Since the download-links page is targeted at more technically-minded users, I propose we model the names off what Debian names their downloads:

**amd64** · **arm64** · armel · **armhf** · **i386** · mips64el · mipsel · ppc64el · s390x

That means "32 bit x86" and "64 bit x86" is out of place compared to the others.

For the homepage, I propose we model it off the Firefox download names. Here we'd use "32-bit" and "64-bit" with hyphens, but qualify with an architecture.

2022-01-30 17:44 UTC, bearbin commented
That sounds fine (although our i386 is actually i686, that's because we inherit the [misname from debian](https://lists.debian.org/debian-devel-announce/2016/05/msg00001.html)).

It will mean more work though to update the buildserver and download links themselves so they're consistent with the names we give them on the download links page.

2022-01-30 19:01 UTC, tigerw commented
Ah I see, then let's forget about download-links for now and I'll just use your suggestion for the home page.

2022-01-30 19:04 UTC, bearbin approved these changes

2022-01-30 19:15 UTC, merged

2022-01-30 19:17 UTC, tigerw commented
Thanks all!