Added link to the real plugin repo
cuberite/cuberite.github.io pull request #78
Opened 2017-08-16 16:25 UTC by williamhatcher

2017-08-16 16:37 UTC, bearbin requested changes

2017-08-16 16:37 UTC, bearbin commented on plugins.html
>  	<a href="https://forum.cuberite.org/forum-2.html" class="button">Download Plugins</a>
The text here doesn't really make sense in connection with the previous line, could you change it?

2017-08-16 17:07 UTC, williamhatcher commented on plugins.html
>  	<a href="https://forum.cuberite.org/forum-2.html" class="button">Download Plugins</a>
Sure.

2017-08-17 12:48 UTC, madmaxoft commented
I don't think the plugin repository is anywhere near being usable, so it's still preferable not to link to it just yet.

2017-08-17 14:12 UTC, bearbin approved these changes

2017-08-17 14:13 UTC, bearbin commented
I have approved this PR - although the plugin repository is not particularly usable at present, I don't believe there is any harm in linking to it in addition to the forum.

2017-08-17 14:14 UTC, madmaxoft commented
Okay then.

2017-08-17 14:14 UTC, merged

2017-08-18 01:54 UTC, williamhatcher commented
Yeah, I figured having both links would cover all bases.